# Usign the Clean Blog theme

title: Louis Peyré
email: gabriel.peyre@ens.fr
description: Site web du peintre Louis Peyré.
baseurl: ""
url: "http://gpeyre.github.io/louispeyre"
github_username:  gpeyre

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["node_modules"]
